eng_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :users do
    # I can't use "users" in original controller name because devise already used
    put 'user_conf/toggle_mode' => 'user_conf#toggle_mode', as: :toggle_mode
  end

  get 'accesses/hello'
  get 'accesses/goodbye'
  get 'dashboard/index'
  get 'sentences/search'
  resources :score_eng_not_writtens
  resources :score_eng_writtens
  resources :scores
  resources :sentences
  root 'accesses#hello'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

eng_app/app/models/score_eng_not_written.rb
class ScoreEngNotWritten < Score
  belongs_to :user
  belongs_to :sentence

  before_create do
    if self.passed
      self.val = 1
    else
      self.val = -1
    end
  end
end

eng_app/app/controllers/score_eng_not_writtens_controller.rb
class ScoreEngNotWrittensController < ApplicationController
  before_action :set_score_eng_not_written, only: [:show, :edit, :update, :destroy]

  # GET /score_eng_not_writtens
  # GET /score_eng_not_writtens.json
  def index
    @score_eng_not_writtens = ScoreEngNotWritten.all
  end

  # GET /score_eng_not_writtens/1
  # GET /score_eng_not_writtens/1.json
  def show
  end

  # GET /score_eng_not_writtens/new
  def new
    @score_eng_not_written = ScoreEngNotWritten.new
  end

  # GET /score_eng_not_writtens/1/edit
  def edit
  end

  # POST /score_eng_not_writtens
  # POST /score_eng_not_writtens.json
  def create
    @score_eng_not_written = ScoreEngNotWritten.new(score_eng_not_written_params)

    respond_to do |format|
      if @score_eng_not_written.save
        format.html { redirect_to @score_eng_not_written, notice: 'Score eng not written was successfully created.' }
        format.json { render :show, status: :created, location: @score_eng_not_written }
      else
        format.html { render :new }
        format.json { render json: @score_eng_not_written.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /score_eng_not_writtens/1
  # PATCH/PUT /score_eng_not_writtens/1.json
  def update
    respond_to do |format|
      if @score_eng_not_written.update(score_eng_not_written_params)
        format.html { redirect_to @score_eng_not_written, notice: 'Score eng not written was successfully updated.' }
        format.json { render :show, status: :ok, location: @score_eng_not_written }
      else
        format.html { render :edit }
        format.json { render json: @score_eng_not_written.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /score_eng_not_writtens/1
  # DELETE /score_eng_not_writtens/1.json
  def destroy
    @score_eng_not_written.destroy
    respond_to do |format|
      format.html { redirect_to score_eng_not_writtens_url, notice: 'Score eng not written was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score_eng_not_written
      @score_eng_not_written = ScoreEngNotWritten.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_eng_not_written_params
      params.fetch(:score_eng_not_written, {}).permit(:passed, :sentence_id, :user_id)
    end
end

eng_app/app/helpers/score_eng_not_writtens_helper.rb
module ScoreEngNotWrittensHelper
end

eng_app/app/views/score_eng_not_writtens/_form.html.erb
<%= form_with(model: score_eng_not_written, local: true) do |form| %>
  <% if score_eng_not_written.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(score_eng_not_written.errors.count, "error") %> prohibited this score_eng_not_written from being saved:</h2>

      <ul>
        <% score_eng_not_written.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

eng_app/app/views/score_eng_not_writtens/edit.html.erb
<h1>Editing Score Eng Not Written</h1>

<%= render 'form', score_eng_not_written: @score_eng_not_written %>

<%= link_to 'Show', @score_eng_not_written %> |
<%= link_to 'Back', score_eng_not_writtens_path %>

eng_app/app/views/score_eng_not_writtens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Score Eng Not Writtens</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @score_eng_not_writtens.each do |score_eng_not_written| %>
      <tr>
        <td><%= link_to 'Show', score_eng_not_written %></td>
        <td><%= link_to 'Edit', edit_score_eng_not_written_path(score_eng_not_written) %></td>
        <td><%= link_to 'Destroy', score_eng_not_written, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score Eng Not Written', new_score_eng_not_written_path %>

eng_app/app/views/score_eng_not_writtens/new.html.erb
<h1>New Score Eng Not Written</h1>

<%= render 'form', score_eng_not_written: @score_eng_not_written %>

<%= link_to 'Back', score_eng_not_writtens_path %>